# Generated by Django 5.1.6 on 2025-05-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergiaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('año', models.IntegerField(default=2025)),
                ('mes', models.IntegerField()),
                ('energia_total_kwh', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'energia_electrica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumoEnergiaTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('año', models.IntegerField(default=2025)),
                ('mes', models.IntegerField()),
                ('consumo_total_glp_kw', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'potencia_activa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionInterfaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_cuadricula', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConexionElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_object_id', models.CharField(max_length=100)),
                ('destino_object_id', models.CharField(max_length=100)),
                ('start_socket', models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='bottom', max_length=10)),
                ('end_socket', models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='top', max_length=10)),
                ('estilo_linea', models.CharField(blank=True, choices=[('cyan-grid', 'Cian Grid'), ('red-straight', 'Rojo Recto'), ('green-fluid', 'Verde Fluido'), ('orange-arc', 'Naranja Arco'), ('blue-magnet', 'Azul Magneto'), ('purple-curve', 'Púrpura Curva'), ('gray-straight', 'Gris Recto'), ('pink-line', 'Rosado Lineal'), ('lime-grid', 'Lima Grid'), ('amber-path', 'Ámbar Camino'), ('ani-pink-grid', '🌀 Rosado Animado Grid'), ('ani-orange-arc', '🌀 Naranja Animado Arco'), ('ani-blue-fluid', '🌀 Azul Animado Fluido'), ('ani-red-straight', '🌀 Rojo Animado Recto'), ('ani-teal-magnet', '🌀 Teal Magneto'), ('ani-indigo-dash', '🌀 Índigo Dash'), ('ani-yellow-blink', '🌀 Amarillo Blink'), ('ani-cyan-fade', '🌀 Cian Fade'), ('ani-green-pulse', '🌀 Verde Pulso'), ('ani-violet-spark', '🌀 Violeta Spark'), ('ani-brown-glow', '🌀 Marrón Glow'), ('ani-charcoal-arc', '🌀 Carbón Arco'), ('ani-maroon-fluid', '🌀 Marrón Fluido'), ('ani-beige-magnet', '🌀 Beige Magnet'), ('ani-navy-curve', '🌀 Azul Marino Curva')], default='cyan-grid', max_length=30, verbose_name='Estilo visual')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_tipo', to='contenttypes.contenttype')),
                ('origen_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_tipo', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MedidorPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_icono_estado', models.BooleanField(default=False)),
                ('tipo_icono_estado', models.CharField(blank=True, default='check', max_length=50)),
                ('fondo_personalizado', models.CharField(blank=True, help_text="Ej: 'transparent', '#0044cc', 'rgba(0,0,0,0.5)'", max_length=50, null=True)),
                ('color_titulo', models.CharField(blank=True, help_text="Ej: 'white', '#FFDD00'", max_length=50, null=True)),
                ('tamano_titulo', models.CharField(blank=True, help_text="Ej: '16px'", max_length=10, null=True)),
                ('fuente_titulo', models.CharField(blank=True, help_text="Ej: 'Arial', 'Verdana'", max_length=100, null=True)),
                ('bold_titulo', models.BooleanField(default=False)),
                ('alineacion_vertical', models.CharField(choices=[('top', 'Arriba'), ('center', 'Centro'), ('bottom', 'Abajo')], default='center', max_length=10)),
                ('medidor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.FloatField(default=4575.3279)),
                ('y', models.FloatField(default=1941.9883)),
                ('seccion', models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General Flota', 'General Flota'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='Vista General Planta', max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('M', 'Medido'), ('C', 'Calculado'), ('', 'Sin tipo')], default='M', max_length=1)),
                ('tipo_descripcion', models.CharField(blank=True, help_text='Texto que aparece al pasar el mouse sobre el tipo (M o C)', max_length=200, null=True)),
                ('categoria_visual', models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto')], default='medidor', max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('grafana_url', models.URLField(blank=True, null=True)),
                ('seccion_destino', models.CharField(blank=True, choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General Flota', 'General Flota'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], max_length=100, null=True)),
                ('width', models.CharField(blank=True, default='100px', max_length=10, null=True)),
                ('height', models.CharField(blank=True, default='100px', max_length=10, null=True)),
                ('background', models.CharField(blank=True, default='transparent', max_length=50, null=True)),
                ('border_color', models.CharField(blank=True, max_length=50, null=True)),
                ('border_width', models.CharField(blank=True, default='0px', max_length=10, null=True)),
                ('border_radius', models.CharField(blank=True, default='0px', max_length=10, null=True)),
                ('border_style', models.CharField(blank=True, choices=[('solid', 'Sólido'), ('dashed', 'Guiones'), ('dotted', 'Punteado'), ('double', 'Doble'), ('groove', 'Surco')], default='solid', max_length=20, null=True)),
                ('animate_class', models.CharField(blank=True, max_length=100, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('text_color', models.CharField(blank=True, default='#000000', max_length=20, null=True)),
                ('font_size', models.CharField(blank=True, default='16px', max_length=10, null=True)),
                ('text_align', models.CharField(blank=True, choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=20, null=True)),
                ('text_vertical_align', models.CharField(blank=True, choices=[('start', 'Arriba'), ('center', 'Centro'), ('end', 'Abajo')], default='center', max_length=20, null=True)),
                ('font_weight', models.CharField(blank=True, choices=[('normal', 'Normal'), ('bold', 'Negrita')], default='normal', max_length=20, null=True)),
                ('font_style', models.CharField(blank=True, choices=[('normal', 'Normal'), ('italic', 'Cursiva')], default='normal', max_length=20, null=True)),
                ('text_decoration', models.CharField(blank=True, choices=[('none', 'Ninguno'), ('underline', 'Subrayado')], default='none', max_length=20, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_medidorposicion',
                'constraints': [models.UniqueConstraint(fields=('medidor_id', 'seccion'), name='unique_medidor_por_seccion')],
            },
        ),
    ]
