# Generated by Django 5.1.6 on 2025-04-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergiaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('año', models.IntegerField(default=2025)),
                ('mes', models.IntegerField()),
                ('energia_total_kwh', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'consumo_energia_electrica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumoEnergiaTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('año', models.IntegerField(default=2025)),
                ('mes', models.IntegerField()),
                ('consumo_total_glp_kw', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
            options={
                'db_table': 'consumo_energia_termica_tabla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedidorPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor_id', models.CharField(max_length=50)),
                ('x', models.FloatField(default=4575.3279)),
                ('y', models.FloatField(default=1941.9883)),
                ('seccion', models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General Flota', 'General Flota'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='Vista General Planta', max_length=100)),
                ('tipo', models.CharField(choices=[('M', 'Medido'), ('C', 'Calculado')], default='M', max_length=1)),
                ('categoria_visual', models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título')], default='medidor', max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('grafana_url', models.URLField(blank=True, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_medidorposicion',
                'constraints': [models.UniqueConstraint(fields=('medidor_id', 'seccion'), name='unique_medidor_por_seccion')],
            },
        ),
        migrations.CreateModel(
            name='ConexionMedidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_socket', models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='bottom', max_length=10, verbose_name='Socket origen')),
                ('end_socket', models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='top', max_length=10, verbose_name='Socket destino')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='core.medidorposicion', verbose_name='Medidor destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='core.medidorposicion', verbose_name='Medidor origen')),
            ],
        ),
    ]
