# Generated by Django 5.1.6 on 2025-05-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto')], default='texto', max_length=50),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='x',
            field=models.FloatField(default=3500.8814),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='y',
            field=models.FloatField(default=1661.5644),
        ),
    ]
