# Generated by Django 5.1.6 on 2025-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='x',
            field=models.FloatField(default=3230.5546),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='y',
            field=models.FloatField(default=1520.8001),
        ),
    ]
