# Generated by Django 5.1.6 on 2025-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_energia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('energia_total', models.DecimalField(decimal_places=1, max_digits=10)),
                ('potencia_actual', models.DecimalField(decimal_places=1, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
