# Generated by Django 5.1.6 on 2025-05-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medidorposicion_categoria_visual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='border_radius',
            field=models.CharField(blank=True, default='5px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='font_weight',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('bold', 'Negrita')], default='Negrita', max_length=20, null=True),
        ),
    ]
