# Generated by Django 5.1.6 on 2025-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medidorposicion_x_alter_medidorposicion_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='border_width',
            field=models.CharField(blank=True, default='1px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='height',
            field=models.CharField(blank=True, default='25px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='width',
            field=models.CharField(blank=True, default='25px', max_length=10, null=True),
        ),
    ]
