# Generated by Django 5.1.6 on 2025-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergiaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('energia_total_kwh', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoEnergiaTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('consumo_total_glp_kw', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MedidorEnergia',
        ),
    ]
