# Generated by Django 5.1.6 on 2025-04-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consumoenergiaelectrica_consumoenergiatermica_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumoenergiaelectrica',
            table='consumo_energia_electrica',
        ),
        migrations.AlterModelTable(
            name='consumoenergiatermica',
            table='consumo_energia_termica_tabla',
        ),
    ]
