# Generated by Django 5.1.6 on 2025-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_medidorposicion_font_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto')], default='energia_sola', max_length=50),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='seccion',
            field=models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General Flota', 'General Flota'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='General Flota', max_length=100),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='x',
            field=models.FloatField(default=10300.0),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='y',
            field=models.FloatField(default=5526.5644),
        ),
    ]
