# Generated by Django 5.1.6 on 2025-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consumoenergiaelectrica_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor_id', models.CharField(max_length=100, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
