# Generated by Django 5.1.6 on 2025-04-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medidor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medidor',
        ),
        migrations.DeleteModel(
            name='MedidorPosicion',
        ),
    ]
