# Generated by Django 5.1.6 on 2025-04-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medidorposicion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedidorPosicion',
        ),
    ]
