# Generated by Django 5.1.6 on 2025-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_medidorposicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionMedidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_id', models.CharField(max_length=50)),
                ('destino_id', models.CharField(max_length=50)),
                ('start_socket', models.CharField(default='bottom', max_length=20)),
                ('end_socket', models.CharField(default='top', max_length=20)),
            ],
        ),
    ]
