# Generated by Django 5.1.6 on 2025-05-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_conexionelemento_estilo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='x',
            field=models.FloatField(default=13800.0),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='y',
            field=models.FloatField(default=5531.0),
        ),
    ]
