# Generated by Django 5.1.6 on 2025-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_medidorposicion_x_alter_medidorposicion_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='background',
            field=models.CharField(blank=True, default='write', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='seccion',
            field=models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General', 'General'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='Flota', max_length=100),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='seccion_destino',
            field=models.CharField(blank=True, choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General', 'General'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='width',
            field=models.CharField(blank=True, default='300px', max_length=10, null=True),
        ),
    ]
