# Generated by Django 5.1.6 on 2025-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_medidorposicion_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto')], default='energia_sola', max_length=50),
        ),
    ]
