# Generated by Django 5.1.6 on 2025-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_medidorposicion_categoria_visual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='seccion',
            field=models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General', 'General'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='Sala de Calderas', max_length=100),
        ),
    ]
