# Generated by Django 5.1.6 on 2025-05-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_medidorposicion_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidorposicion',
            name='z_index',
            field=models.IntegerField(blank=True, help_text='Valor de z-index para controlar la superposición. Ej: 10, 100, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='conexionelemento',
            name='end_socket',
            field=models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='left', max_length=10),
        ),
        migrations.AlterField(
            model_name='conexionelemento',
            name='estilo_linea',
            field=models.CharField(blank=True, choices=[('azul-solido', 'Azul-solido'), ('yellow-straight', 'Amarillo Solido'), ('green-fluid', 'Verde Fluido'), ('orange-arc', 'Naranja Arco'), ('blue-magnet', 'Azul Magneto'), ('purple-curve', 'Púrpura Curva'), ('gray-straight', 'Gris Recto'), ('pink-line', 'Rosado Lineal'), ('lime-grid', 'Lima Grid'), ('amber-path', 'Ámbar Camino'), ('ani-pink-grid', '🌀 Gris Animado Grid'), ('ani-orange-arc', '🌀 Naranja Animado Grid'), ('ani-blue-fluid', '🌀 Azul Animado Grid'), ('ani-red-straight', '🌀 Rojo Animado Grid'), ('ani-green-magnet', '🌀 Verde Animado Grid'), ('ani-yellow-dash', '🌀 Amarillo Animado Grid'), ('ani-yellow-blink', '🌀 Amarillo Blink'), ('ani-cyan-fade', '🌀 Cian Fade'), ('ani-green-pulse', '🌀 Verde Pulso'), ('ani-violet-spark', '🌀 Violeta Spark'), ('ani-brown-glow', '🌀 Marrón Glow'), ('ani-charcoal-arc', '🌀 Carbón Arco'), ('ani-maroon-fluid', '🌀 Marrón Fluido'), ('ani-beige-magnet', '🌀 Beige Magnet'), ('ani-navy-curve', '🌀 Azul Marino Curva')], default='ani-orange-arc', max_length=30, verbose_name='Estilo visual'),
        ),
        migrations.AlterField(
            model_name='conexionelemento',
            name='start_socket',
            field=models.CharField(blank=True, choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha')], default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='background',
            field=models.CharField(blank=True, default='white', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto'), ('contenedor', 'Contenedor')], default='texto', max_length=50),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='height',
            field=models.CharField(blank=True, default='38px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='seccion',
            field=models.CharField(choices=[('Vista General Planta', 'Vista General Planta'), ('Empalme 1 Planta Harina', 'Empalme 1 Planta Harina'), ('Empalme 2 Planta Congelado', 'Empalme 2 Planta Congelado'), ('Empalme 3 Pontón Tor', 'Empalme 3 Pontón Tor'), ('General', 'General'), ('Sala de Calderas', 'Sala de Calderas'), ('Planta Harina', 'Planta Harina'), ('Planta Congelado', 'Planta Congelado'), ('Flota', 'Flota'), ('Planta Harina/Congelados', 'Planta Harina/Congelados')], default='Planta Congelado', max_length=100),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='text_vertical_align',
            field=models.CharField(blank=True, choices=[('start', 'Arriba'), ('center', 'Centro'), ('end', 'Abajo')], default='start', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='width',
            field=models.CharField(blank=True, default='270px', max_length=10, null=True),
        ),
    ]
