# Generated by Django 5.1.6 on 2025-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_medidorposicion_energia_total_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidorposicion',
            name='flujo_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fijo si no se consulta por API', max_digits=12),
        ),
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto'), ('contenedor', 'Contenedor'), ('contenedor-10', 'Contenedor-10'), ('contenedor-100', 'Contenedor-100'), ('medidorestermicos', 'Medidorestermicos')], default='texto', max_length=50),
        ),
    ]
