# Generated by Django 5.1.6 on 2025-05-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_medidorposicion_flujo_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidorposicion',
            name='flujo_actual',
        ),
        migrations.AddField(
            model_name='medidorposicion',
            name='mostrar_flujometro',
            field=models.BooleanField(default=False, help_text='Si está activado, mostrará el valor de flujómetro en la tarjeta visual'),
        ),
    ]
