# Generated by Django 5.1.6 on 2025-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_medidorposicion_flujo_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidorposicion',
            name='categoria_visual',
            field=models.CharField(blank=True, choices=[('medidor', 'Medidor'), ('titulo', 'Título'), ('energia_sola', 'Solo Energía'), ('texto', 'Texto'), ('contenedor', 'Contenedor'), ('contenedor-10', 'Contenedor-10'), ('contenedor-100', 'Contenedor-100'), ('medidorglp', 'Medidor GLP'), ('medidordiesel', 'Medidor Diésel'), ('medidorvapor', 'Medidor de Vapor'), ('medidorflujometro', 'Medidor de Flujometro')], default='texto', max_length=50),
        ),
    ]
