# Generated by Django 5.1.6 on 2025-05-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_medidorposicion_categoria_visual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidorposicion',
            name='mostrar_flujometro',
        ),
        migrations.AddField(
            model_name='medidorposicion',
            name='kg_totalizador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fijo si no se consulta por API', max_digits=12),
        ),
    ]
